GET http://localhost:9876/test-http-code

###
GET http://localhost:9876/hello2

###
GET http://localhost:8082/download-file
#Range: bytes=0-1
###

GET http://localhost:9876/hello

###

GET http://localhost:9876/proxy-get-request
X-Request-Id: 112233

###

GET http://localhost:9876/date-header

###

GET http://localhost:8082/hello

###
POST http://localhost:8082/actuator/gateway/refresh

###
GET http://localhost:8081/get-result-and-audit

###
POST http://localhost:10012/sowa_validate_json
Content-Type: application/json

{
  "field_11": "value_1",
  "field_2": "value_2",
  "field_3": "asd"
}

###
POST http://localhost:10012/sowa_validate_xsd
Content-Type: application/xml

<Request xmlns="http://bssys.com/upg/request" mySenderKey="asd"/>

###
POST http://localhost:10012/ott-service/TokenJsonRpcFacade.json
Content-Type: application/json

{
  "a": "b"
}

###
GET http://localhost:9876/get-or-create-ignite-cache

###
GET http://localhost:9876/get-ignite-cache-statistics

###
GET http://localhost:9876/destroy-ignite-cache

###
GET http://localhost:9876/get-or-create-ignite-cache-with-peer-class-loading

###
GET http://localhost:9876/not-exists-url

###
POST http://sender:1111/post
Content-Type: application/x-www-form-urlencoded

param1=Param1+some+value&param2=%3Casd%3E


###

GET http://localhost:9876/test-kafka







###
GET http://localhost:10013/get-some-json

###
GET http://localhost:10013/get-empty-json

###
GET http://localhost:10013/get-invalid-json




###
GET http://localhost:10013/get-some-xml

###
GET http://localhost:10013/get-text-xml

###
GET http://localhost:10013/get-empty-xml

###
GET http://localhost:10013/get-invalid-xml









###
 GET http://localhost:10013/get-empty-body

###
GET http://localhost:10013/with-param?param1=asdsad

###
GET http://localhost:10013/download-virus

###
GET http://localhost:9876/download-base64-virus

###
GET http://localhost:10013/fake-response-content-type



###
GET http://httpbin.org/get


###
GET http://localhost:9876/hello_with_sleep

###
POST http://localhost:9876/v1/files/upload

###
POST http://localhost:9876/apache-commons-upload-to-file
Content-Type: multipart/form-data; boundary=abcd

--abcd
Content-Disposition: form-data; name="text"; filename="input.txt"

Text123
--abcd--

###
### curl -v -F 'filename1=@/Users/17230726/IdeaProjects/test_all/test_file.txt' http://localhost:9876/single-file-upload
### *   Trying 127.0.0.1:9876...
### * Connected to localhost (127.0.0.1) port 9876 (#0)
### > POST /single-file-upload HTTP/1.1
### > Host: localhost:9876
### > User-Agent: curl/7.79.1
### > Accept: */*
### > Content-Length: 220
### > Content-Type: multipart/form-data; boundary=------------------------75c92102b1b9b35e
### >
### * We are completely uploaded and fine
### * Mark bundle as not supporting multiuse
### < HTTP/1.1 200
### < Content-Type: text/plain;charset=UTF-8
### < Content-Length: 10
### < Date: Fri, 30 Dec 2022 15:00:39 GMT
### <
### * Connection #0 to host localhost left intact
###
POST http://localhost:9876/single-file-upload
Content-Type: multipart/form-data; boundary=abcd

--abcd
Content-Disposition: form-data; name="filename1"; filename="input.txt"
#Content-Type: text/plain

TextAAA
--abcd--

###
POST http://localhost:9876/v1/payments
Content-Type: application/json
Authorization: Bearer 123321

{
  "number": "occaecat in elit",
  "date": "1935-01-11",
  "digestSignatures": [
    {
      "certificateUuid": "a44ebab9-2dea-d47f-e360-8e5659675740",
      "base64Encoded": "labore dolor"
    },
    {
      "certificateUuid": "26533dab-2cc2-cec3-b727-2f599f67d3bb",
      "base64Encoded": "sunt ullamco"
    }
  ],
  "bankStatus": "officia qui",
  "bankComment": "velit in ut nisi ipsum",
  "externalId": "3bbca2aa-0cf8-207a-b8bc-6e554485e700",
  "amount": 61705369,
  "operationCode": "01",
  "deliveryKind": "электронно",
  "priority": "3",
  "urgencyCode": "esse Duis sit",
  "voCode": "07048",
  "purpose": "cupidatat ea",
  "departmentalInfo": {
    "voluptate310": "eiusmod ut do",
    "drawerStatus101": "m",
    "kbk": "29Q9GQAWWGC4NCGE64",
    "reasonCode106": "n"
  },
  "payerName": "Duis cupidatat culpa commodo qui",
  "payerInn": "344632710344",
  "payerKpp": "364884750",
  "payerAccount": "52072169266868372905",
  "payerBankBic": "948736350",
  "payerBankCorrAccount": "35430077892613671501",
  "payeeName": "consequat occaecat adipisicing",
  "payeeInn": "34347",
  "payeeKpp": "0",
  "payeeAccount": "70547945528139015843",
  "payeeBankBic": "943113014",
  "payeeBankCorrAccount": "47115436719069980870",
  "crucialFieldsHash": "ullamco dolor pariatur ipsum Lorem",
  "vat": {
    "type": "NO_VAT",
    "rate": "5",
    "amount": 58097507
  },
  "incomeTypeCode": "n",
  "isPaidByCredit": false,
  "creditContractNumber": "minim"
}